language: python
python: 
  - "3.6"

env:
  global:
    - SECRET_KEY='QeVYWfId8LODTNgMRl4-hnAdBYdhuZy_7o9RlfaUKhWdl2G5xEVXfYaEEbJ8QWnNeiDGgQn6wjGmscU7wAVhrA'
    - TEST_DATABASE_URL='postgresql://erycoking:king*1234@127.0.0.1/test_politico'
  
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_politico;" -U postgres
  - psql -c "CREATE USER erycoking WITH PASSWORD 'king*1234';" -U postgres

# command to run tests
script:
  - pytest
  - pytest --cov=politico

after_success:
  - coveralls
