language: python
python: 
  - "3.6"

env:
  - export FLASK_RUN=run.py
  - export DATABASE_URL='postgresql://erycoking:@127.0.0.1/politico'
  - export SECRET_KEY='QeVYWfId8LODTNgMRl4-hnAdBYdhuZy_7o9RlfaUKhWdl2G5xEVXfYaEEbJ8QWnNeiDGgQn6wjGmscU7wAVhrA'
  - export TEST_DATABASE_URL='postgresql://erycoking:@127.0.0.1/test_politico'
  - export FLASK_ENV=development
  
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database politico;' -U postgres
  - psql -c 'create database test_politico;' -U postgres
  
# command to run tests
script:
  - pytest
  - pytest --cov=politico

after_success:
  - coveralls
